/*
 * Maps sdkconfig (menuconfig) options to compile-time macros used across ESPD.
 */
#pragma once

#include "sdkconfig.h"

#define IOCHANS CONFIG_ESPD_IOCHANS

#if CONFIG_ESPD_USE_ADC
#define USEADC 1
#endif

#if CONFIG_ESPD_PD_USE_WIFI
#define PD_USE_WIFI 1
#endif

#if CONFIG_ESPD_PD_USE_CONSOLE
#define PD_USE_CONSOLE 1
#endif

#if CONFIG_ESPD_PD_USE_SDCARD
#define PD_USE_SDCARD 1
#endif

#if CONFIG_ESPD_PD_USE_ANALOG0
#define PD_USE_ANALOG0 1
#endif

#if CONFIG_ESPD_PD_USE_TOUCH0
#define PD_USE_TOUCH0 1
#endif

#if CONFIG_ESPD_PD_INCLUDEPATCH
#define PD_INCLUDEPATCH 1
#endif

#ifdef CONFIG_ESPD_SKIP_WIFI_WHEN_MAIN_PD_ON_DISK
#define ESPD_SKIP_WIFI_WHEN_MAIN_PD_ON_DISK 1
#else
#define ESPD_SKIP_WIFI_WHEN_MAIN_PD_ON_DISK 0
#endif

#ifdef CONFIG_ESPD_ENABLE_LEGACY_WIFI_TRANSPORT
#define ESPD_ENABLE_LEGACY_WIFI_TRANSPORT 1
#else
#define ESPD_ENABLE_LEGACY_WIFI_TRANSPORT 0
#endif

#define ESPD_AOUT_NUM_CHANNELS CONFIG_ESPD_AOUT_NUM_CHANNELS
#define ESPD_AOUT_PIN_0 CONFIG_ESPD_AOUT_PIN_0
#define ESPD_AOUT_PIN_1 CONFIG_ESPD_AOUT_PIN_1
#define ESPD_AOUT_PWM_FREQ_HZ CONFIG_ESPD_AOUT_PWM_FREQ_HZ
#define ESPD_ANALOG_TASK_PERIOD_MS CONFIG_ESPD_ANALOG_TASK_PERIOD_MS

#define ESPD_TOUCH_NUM_CHANNELS CONFIG_ESPD_TOUCH_NUM_CHANNELS
#define ESPD_TOUCH_PIN_0 CONFIG_ESPD_TOUCH_PIN_0
#define ESPD_TOUCH_PIN_1 CONFIG_ESPD_TOUCH_PIN_1
#define ESPD_TOUCH_PIN_2 CONFIG_ESPD_TOUCH_PIN_2
#define ESPD_TOUCH_PIN_3 CONFIG_ESPD_TOUCH_PIN_3
#define ESPD_TOUCH_PIN_4 CONFIG_ESPD_TOUCH_PIN_4
#define ESPD_TOUCH_PIN_5 CONFIG_ESPD_TOUCH_PIN_5
#define ESPD_TOUCH_PIN_6 CONFIG_ESPD_TOUCH_PIN_6
#define ESPD_TOUCH_PIN_7 CONFIG_ESPD_TOUCH_PIN_7
#define ESPD_TOUCH_TASK_PERIOD_MS CONFIG_ESPD_TOUCH_TASK_PERIOD_MS
#define ESPD_TOUCH_REPORT_EVERY_N_BLOCKS CONFIG_ESPD_TOUCH_REPORT_EVERY_N_BLOCKS

#if CONFIG_ESPD_BOARD_GENERIC
#define PIN_BIT_CLOCK CONFIG_ESPD_GENERIC_I2S_BCLK
#define PIN_WORD_SELECT CONFIG_ESPD_GENERIC_I2S_WS
#define PIN_DATA_OUT CONFIG_ESPD_GENERIC_I2S_DOUT
#define PIN_DATA_IN CONFIG_ESPD_GENERIC_I2S_DIN
#endif
