/*
 * Maps sdkconfig (menuconfig) options to compile-time macros used across ESPD.
 */
#pragma once

#include <sdkconfig.h>

#define IOCHANS CONFIG_ESPD_IOCHANS

#if CONFIG_ESPD_USE_ADC
#define ESPD_USE_ADC 1
#endif

#if CONFIG_ESPD_USE_WIFI
#define ESPD_USE_WIFI 1
#endif

#if CONFIG_ESPD_USE_SDCARD
#define ESPD_USE_SDCARD 1
#endif

#if CONFIG_ESPD_DEV_SYNC
#define ESPD_DEV_SYNC 1
#endif

#if CONFIG_ESPD_DEV_CDC_SYNC
#define ESPD_DEV_CDC_SYNC 1
#endif

#if CONFIG_ESPD_DEV_SERIAL_SYNC
#define ESPD_DEV_SERIAL_SYNC 1
#endif

#if CONFIG_ESPD_USE_AIN
#define ESPD_USE_AIN 1
#endif

#if CONFIG_ESPD_USE_TOUCH
#define ESPD_USE_TOUCH 1
#endif

#if CONFIG_ESPD_WIFI_AP_SYNC
#define ESPD_WIFI_AP_SYNC 1
#endif

#if CONFIG_ESPD_USE_AOUT
#define ESPD_USE_AOUT 1
#endif

#if CONFIG_ESPD_USE_DIN
#define ESPD_USE_DIN 1
#endif

#if CONFIG_ESPD_USE_DOUT
#define ESPD_USE_DOUT 1
#endif

#ifdef CONFIG_ESPD_ENABLE_LEGACY_WIFI_TRANSPORT
#define ESPD_ENABLE_LEGACY_WIFI_TRANSPORT 1
#else
#define ESPD_ENABLE_LEGACY_WIFI_TRANSPORT 0
#endif

#if CONFIG_ESPD_BOARD_GENERIC
#define PIN_BIT_CLOCK CONFIG_ESPD_GENERIC_I2S_BCLK
#define PIN_WORD_SELECT CONFIG_ESPD_GENERIC_I2S_WS
#define PIN_DATA_OUT CONFIG_ESPD_GENERIC_I2S_DOUT
#define PIN_DATA_IN CONFIG_ESPD_GENERIC_I2S_DIN
#endif
