/*
 * Waveshare board: ESPD-specific constants (BSP header not required here).
 */
#pragma once

#define ESPD_WAVESHARE_LED_GPIO 38
#define ESPD_WAVESHARE_LED_COUNT 7
#define ESPD_WAVESHARE_TCA9555_I2C_ADDR 0x20

#define ESPD_WAVESHARE_LED_BOOT_R 0
#define ESPD_WAVESHARE_LED_BOOT_G 0
#define ESPD_WAVESHARE_LED_BOOT_B 0

#define ESPD_WAVESHARE_SD_PIN_CLK 40
#define ESPD_WAVESHARE_SD_PIN_CMD 42
#define ESPD_WAVESHARE_SD_PIN_D0 41

#ifndef ESPD_WAVESHARE_BUTTON0_PORT1_BIT
#define ESPD_WAVESHARE_BUTTON0_PORT1_BIT 1
#endif
#ifndef ESPD_WAVESHARE_BUTTON1_PORT1_BIT
#define ESPD_WAVESHARE_BUTTON1_PORT1_BIT 2
#endif
#ifndef ESPD_WAVESHARE_BUTTON2_PORT1_BIT
#define ESPD_WAVESHARE_BUTTON2_PORT1_BIT 3
#endif

#define ESPD_LED_MAX_BRIGHTNESS 255
#define ESPD_AOUT_PWM_FALLBACK_FREQ_HZ 10000
