name: Build ESPD firmware

on:
  push:
    branches:
      - main
      - master
      - feature/ci
    tags:
      - '**'
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Generic ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [esp32, esp32s3]
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Apply required Pd patches
        run: ./scripts/apply-pd-patches.sh

      - name: Build Generic firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.1
          target: ${{ matrix.target }}
          command: idf.py set-target ${{ matrix.target }} build

      - name: Upload firmware as action artifact
        uses: actions/upload-artifact@v4
        with:
          name: espd-generic-${{ matrix.target }}-${{ github.sha }}
          path: |
            build/espd.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/flash_args

      - name: Upload firmware to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/espd.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
            build/flash_args
