name: Build Waveshare firmware

on:
  push:
    branches:
      - waveshare

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0.1
          target: esp32s3
          command: >-
            export ESPD_BOARD=waveshare_s3 &&
            idf.py set-target esp32s3 &&
            idf.py fullclean build
